export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS';
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS';
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS';
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
