export const DELETE_YIELD_SUCCESS = 'DELETE_YIELD_SUCCESS';
export const CREATE_YIELD_SUCCESS = 'CREATE_YIELD_SUCCESS';

export const GET_INFLATION_RATES_SUCCESS = 'GET_INFLATION_RATES_SUCCESS';
export const CREATE_INFLATION_RATE_SUCCESS = 'CREATE_INFLATION_RATE_SUCCESS';
export const UPDATE_INFLATION_RATE_SUCCESS = 'UPDATE_INFLATION_RATE_SUCCESS';
export const DELETE_INFLATION_RATE_SUCCESS = 'DELETE_INFLATION_RATE_SUCCESS';
