export const GET_INCOMES_SUCCESS = 'GET_INCOMES_SUCCESS';
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS';
export const UPDATE_INCOME_SUCCESS = 'UPDATE_INCOME_SUCCESS';
export const DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';
