export const GET_LIABILITIES_SUCCESS = 'GET_LIABILITIES_SUCCESS';
export const CREATE_LIABILITY_SUCCESS = 'CREATE_LIABILITY_SUCCESS';
export const UPDATE_LIABILITY_SUCCESS = 'UPDATE_LIABILITY_SUCCESS';
export const DELETE_LIABILITY_SUCCESS = 'DELETE_LIABILITY_SUCCESS';
